version: '3.9'

networks:
  main:
    name: sw-galaxy-form

services:
  apache:
    image: httpd:latest
    container_name: sw-galaxy-form
    ports:
    - '8080:80'
    volumes:
    - ./:/usr/local/apache2/htdocs
    networks:
      - main