# Use the official Node.js image
FROM node:20

# Set working directory inside container
WORKDIR /app

# Copy optimizer script
COPY ./prod-pipeline/source-to-prod.sh ./prod-pipeline/

RUN chmod +x ./scripts/source-to-prod.sh 

# Install minification/optimization tools globally
RUN npm install -g \
    uglify-js \
    csso-cli \
    html-minifier-terser \
    svgo \
    jsonminify

# Expose port if needed (for web server)
EXPOSE 8080

VOLUME [ "/app" ]

# Default command : process code into prod ready files
CMD ./prod-pipeline/source-to-prod.sh

