version: '3.9'

networks:
  frontend:
    name: ${APP_NAME}-frontend

services:
  web:
    image: ${IMAGE_NAME}
    container_name: ${APP_NAME}-web
    restart: ${RESTART_POLICY}
    ports:
    - '${HOST_PORT}:${CONTAINER_PORT}'
    volumes:
    - ./:/usr/local/apache2/htdocs
    networks:
      - frontend